const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]);
scripts.forEach(s=>new vm.Script(s));
const Game=vm.runInNewContext(scripts[0]+';Game');
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
function setup(){let g=new Game(()=>0.5);g.start([Array(10).fill(2),Array(10).fill(2)],0);return g;}
function hero(g,i,slot){let p=g.players[i],c=p.hand.find(c=>c.type==='hero')||p.deck.find(c=>c.type==='hero');p.hand=p.hand.filter(x=>x!==c);p.deck=p.deck.filter(x=>x!==c);p.field[slot]=c;return c;}
function live(){let g=setup();hero(g,0,0);hero(g,1,0);g.stage='start';g.startStep=0;g.active=g.viewer=0;g.turn=1;return g;}
function handCard(g,type){let p=g.players[0],c=p.hand.find(c=>c.type===type);if(!c){c=p.deck.find(c=>c.type===type);p.deck=p.deck.filter(x=>x!==c);p.hand.push(c);}return c;}
function values(g){return Object.fromEntries(g.players.flatMap(p=>p.field.filter(Boolean).map(c=>[c.uid,c.hp])));}
test('deck validation rejects wrong size and copies',()=>{assert.throws(()=>new Game().start([Array(10).fill(1),Array(10).fill(2)],0));let a=Array(10).fill(2);a[0]=3;a[1]=1;assert.throws(()=>new Game().start([a,Array(10).fill(2)],0));});
test('initial health, real decks and four cards',()=>{let g=setup();for(let p of g.players){assert.equal(p.health,20);assert.equal(p.deck.length,16);assert.equal(p.hand.length,4);assert.equal(new Set([...p.deck,...p.hand].map(c=>c.uid)).size,20);}});
test('both invalid hands redraw without bonus and preserve all cards',()=>{let g=setup();for(let p of g.players){let all=[...p.deck,...p.hand];p.hand=all.filter(c=>c.type!=='hero').slice(0,4);p.deck=all.filter(c=>!p.hand.includes(c));}g.stage='mulligan';g.redraw();assert.equal(g.bonus,null);for(let p of g.players){assert.equal(p.hand.length,4);assert.equal(p.deck.length,16);}});
test('only eligible opponent receives optional bonus',()=>{let g=setup();for(let [i,p] of g.players.entries()){let all=[...p.deck,...p.hand];p.hand=all.filter(c=>i===0?c.type==='hero':c.type!=='hero').slice(0,4);p.deck=all.filter(c=>!p.hand.includes(c));}g.stage='mulligan';g.redraw();assert.equal(g.bonus.player,0);g.chooseBonus(true);assert.equal(g.players[0].hand.length,5);assert.equal(g.players[0].deck.length,15);});
test('single face-down hero each and simultaneous reveal',()=>{let g=setup();for(let p of g.players){let all=[...p.deck,...p.hand];p.hand=all.filter(c=>c.type==='hero').slice(0,4);p.deck=all.filter(c=>!p.hand.includes(c));}g.stage='deploy';g.deploy(g.players[0].hand[0].uid,7);assert.throws(()=>g.deploy(g.players[0].hand[0].uid,6));g.confirmDeploy();g.deploy(g.players[1].hand[0].uid,2);g.confirmDeploy();assert.equal(g.stage,'reveal');g.reveal();assert.equal(g.active,0);assert.equal(g.stage,'start');});
test('replenish to hero cap, draw exactly once',()=>{let g=live();hero(g,0,1);hero(g,0,2);g.players[0].actions=1;let n=g.players[0].deck.length;g.begin();assert.equal(g.players[0].actions,3);assert.equal(g.players[0].deck.length,n-1);assert.throws(()=>g.begin());g.main();assert.equal(g.stage,'main');});
test('hero deployment costs one and requires own empty slot',()=>{let g=live();g.begin();g.main();let c=handCard(g,'hero');assert.throws(()=>g.play(c.uid,0));assert.throws(()=>g.play(c.uid,8));assert.equal(g.players[0].actions,1);g.play(c.uid,1);assert.equal(g.players[0].actions,0);assert.equal(g.players[0].field[1].uid,c.uid);});
test('movement prevents diagonal, wraparound, occupied and repeat',()=>{let g=live();g.stage='main';g.players[0].actions=5;assert.throws(()=>g.move(0,5));g.move(0,1);assert.throws(()=>g.move(1,2));assert.equal(g.players[0].actions,4);g.players[0].field[1].moved=false;hero(g,0,2);assert.throws(()=>g.move(1,2));g.players[0].field[3]=g.players[0].field[1];g.players[0].field[1]=null;assert.throws(()=>g.move(3,4));});
test('equipment validates eligibility and attaches below hero',()=>{let g=live();g.stage='main';g.players[0].actions=2;let c=handCard(g,'equipment');assert.throws(()=>g.play(c.uid,0,false));g.play(c.uid,0,true);assert.equal(g.players[0].field[0].attached[0].uid,c.uid);assert.equal(g.players[0].actions,1);});
test('item costs one, locks actions, discards after settlement',()=>{let g=live();g.stage='main';g.players[0].actions=2;let c=handCard(g,'item');g.play(c.uid);assert.equal(g.players[0].discard.length,0);assert.throws(()=>g.end());assert.throws(()=>g.move(0,1));g.settle(values(g));assert.equal(g.players[0].discard[0].uid,c.uid);assert.equal(g.players[0].actions,1);});
test('skill requires confirmation and available action',()=>{let g=live();g.stage='main';g.players[0].actions=1;assert.throws(()=>g.skill(0,false));g.skill(0,true);assert.equal(g.players[0].actions,0);g.settle(values(g));assert.throws(()=>g.skill(0,true));});
test('zero HP discards hero and attachments; no hero loses',()=>{let g=live();g.stage='main';g.players[0].actions=3;let c=handCard(g,'equipment');g.play(c.uid,0,true);g.skill(0,true);let v=values(g);v[g.players[0].field[0].uid]=0;g.settle(v);assert.equal(g.players[0].discard.length,2);assert.equal(g.stage,'over');assert.equal(g.winner,1);});
test('simultaneous loss and card exceptions pause for ruling',()=>{for(let exception of [false,true]){let g=live();g.stage='main';g.players[0].actions=1;g.skill(0,true);let v=values(g);v[g.players[0].field[0].uid]=0;if(!exception)v[g.players[1].field[0].uid]=0;g.settle(v,exception);assert.ok(g.blocked);assert.notEqual(g.stage,'over');}});
test('end is free, actions persist and turn passes',()=>{let g=live();g.stage='main';g.players[0].actions=1;g.players[1].field[0].moved=true;g.end();assert.equal(g.players[0].actions,1);g.pass();assert.equal(g.active,1);assert.equal(g.stage,'start');assert.equal(g.players[0].actions,1);assert.equal(g.players[1].field[0].moved,false);});
test('stage effects gate transitions without base action charge',()=>{let g=live();g.begin();g.phaseEffect();assert.throws(()=>g.main());g.settle(values(g));g.main();g.end();g.phaseEffect();assert.throws(()=>g.pass());g.settle(values(g));assert.equal(g.players[0].actions,1);g.pass();});
test('empty deck pauses; start-phase refill never exceeds current cap',()=>{let g=live();g.players[0].deck=[];g.begin();assert.ok(g.blocked);assert.throws(()=>g.main());let h=live();h.players[0].actions=3;h.begin();assert.equal(h.blocked,null);assert.equal(h.players[0].actions,1);});
test('invalid settlement is atomic',()=>{let g=live();g.stage='main';g.players[0].actions=1;g.skill(0,true);let v=values(g);v[g.players[1].field[0].uid]=-1;assert.throws(()=>g.settle(v));assert.equal(g.players[0].field[0].hp,4);assert.ok(g.pending);});
console.log(passed+' tests passed; both inline scripts parse successfully.');
